name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/appimages/banner.jpg
    - assets/appimages/chibi gojoxgeto keychain.jpg
    - assets/appimages/dazaixchuyya keychain.jpg
    - assets/appimages/enha circle keychian.jpg
    - assets/appimages/enha fate keychain.jpg
    - assets/appimages/enha geometry keychain.jpg
    - assets/appimages/enha keychain.jpg
    - assets/appimages/enhypen star keychain.jpg
    - assets/appimages/gojo and geto keychain.jpg
    - assets/appimages/gojogeto kitty keychains.jpg
    - assets/appimages/gojoxgeto fish keychain.jpg
    - assets/appimages/gojoxgeto keychain.jpg
    - assets/appimages/gojoxgeto kitty keychains.jpg
    - assets/appimages/heesung doll 01.jpg
    - assets/appimages/heesung doll 02.jpg
    - assets/appimages/heesung doll 03.jpg
    - assets/appimages/hoon doll pink 01.jpg
    - assets/appimages/jake doll.jpg
    - assets/appimages/jake doll 01.jpg
    - assets/appimages/jake doll 02.jpg
    - assets/appimages/jay doll 02.jpg
    - assets/appimages/jay doll 03.jpg
    - assets/appimages/jayy doll 01.jpg
    - assets/appimages/jjk anime keychains.jpg
    - assets/appimages/jungownie doll 01.jpg
    - assets/appimages/jungownie doll 02.jpg
    - assets/appimages/jungwonie doll 03.jpg
    - assets/appimages/leebit 01.jpg
    - assets/appimages/leebit 02.jpg
    - assets/appimages/leebit 03.jpg
    - assets/appimages/leebit 04.jpg
    - assets/appimages/mini gojoxgeto keychain.jpg
    - assets/appimages/ni-ki doll 02.jpg
    - assets/appimages/ni-ki doll 03.jpg
    - assets/appimages/ni-ki puma doll.jpg
    - assets/appimages/orv doll set 02.jpg
    - assets/appimages/orv doll set 03.jpg
    - assets/appimages/orv doll set 04.jpg
    - assets/appimages/orv doll set 05.jpg
    - assets/appimages/orv dolls 01.jpg
    - assets/appimages/paranormal enha keychain.jpg
    - assets/appimages/pink hair sunoo doll.jpg
    - assets/appimages/satosugo kitten keychain.jpg
    - assets/appimages/satosugo shrink kaychain.jpg
    - assets/appimages/satosugu  keychain.jpg
    - assets/appimages/sunghoon doll 01.jpg
    - assets/appimages/sunghoon doll 02.jpg
    - assets/appimages/sunghoon doll 3.jpg
    - assets/appimages/sunghoon doll 04.jpg
    - assets/appimages/sunghoon doll 05.jpg
    - assets/appimages/sunghoon vampire doll.jpg
    - assets/appimages/sunoo doll 01.jpg
    - assets/appimages/sunoo doll 02.jpg
    - assets/appimages/sunoo doll 03.jpg

