// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtEPehxJS6bZ-YV6XRzTT1TVY3tj5eHc',
    appId: '1:721098560901:web:3ce8acc21b1c31e575a0ec',
    messagingSenderId: '721098560901',
    projectId: 'encorev2',
    authDomain: 'encorev2.firebaseapp.com',
    storageBucket: 'encorev2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlntA6Kbu1uQ-j6QCS9d1-L7nEJ100Co',
    appId: '1:721098560901:android:8971b73e648eb1de75a0ec',
    messagingSenderId: '721098560901',
    projectId: 'encorev2',
    storageBucket: 'encorev2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHtEPehxJS6bZ-YV6XRzTT1TVY3tj5eHc',
    appId: '1:721098560901:web:8ec7b74276ada51275a0ec',
    messagingSenderId: '721098560901',
    projectId: 'encorev2',
    authDomain: 'encorev2.firebaseapp.com',
    storageBucket: 'encorev2.firebasestorage.app',
  );
}
